services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      timeout: 30s
      retries: 5
      interval: 10s
      start_period: 30s

  backend:
    image: ashithrahul93/fly-backend:latest
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: myapp_user
      DB_PASSWORD: myapp_password
      DB_NAME: myapp_db
      PORT: 3000
      NODE_ENV: production
    ports:
      - "1001:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: ashithrahul93/fly-frontend:latest
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge